name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux]
        goarch: [amd64, arm64]
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23.5'

    - name: Build
      env:
        GOOS: ${{ matrix.goos }}
        GOARCH: ${{ matrix.goarch }}
      run: go build -o bin/waybar-code-stats-${{ matrix.goos }}-${{ matrix.goarch }} cmd/main.go

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: waybar-code-stats-${{ matrix.goos }}-${{ matrix.goarch }}
        path: bin/waybar-code-stats
