name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux]
        goarch: [amd64, arm64]
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23.5'

    - name: Build
      env:
        GOOS: ${{ matrix.goos }}
        GOARCH: ${{ matrix.goarch }}
      run: |
        mkdir -p release/${{ matrix.goos }}-${{ matrix.goarch }}
        go build -o release/${{ matrix.goos }}-${{ matrix.goarch }}/waybar-code-stats cmd/main.go

    - name: Create archives
      run: |
        cd release
        for dir in *; do
          zip -r "${dir}.zip" "$dir"
        done
        cd ..

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: waybar-code-stats-${{ matrix.goos }}-${{ matrix.goarch }}
        path: release/${{ matrix.goos }}-${{ matrix.goarch }}.zip
